{% set name = "mkdocs-autorefs" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-autorefs-{{ version }}.tar.gz
  sha256: c17f77db766409fbd493dc75668e1e9e0221236b1d18194b961d8b1a7d74b980

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pdm
    - python >=3.7,<4.0
  run:
    - markdown >=3.3
    - mkdocs >=1.1
    - python >=3.7,<4.0

test:
  imports:
    - mkdocs_autorefs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mkdocstrings/autorefs
  summary: Automatically link across pages in MkDocs.
  license: ISC
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
